[phases.setup]
nixPkgs = ["python311", "gcc", "postgresql"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install -r api/requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && cd api && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"